### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by xingbw** [EricTan7/TGP-T#1]
Hi, when will the codes be released?

**Comment by EricTan7** [comment]
> Hi, when will the codes be released?

Thanks for your attention to our work. We plan to release our code within the forthcoming two weeks.

**Comment by xingbw** [comment]
>Thanks for your attention to our work. We plan to release our code within the forthcoming two weeks.

Thanks for your reply!
After reading the paper, I got a few questions willing to have a discussion:
-The prompt is tuned by the supervision from texts, while the texts are generated from MiniGPT,  so is it reasonable to say that the prompt learning actually benefits from MiniGPT?
-Instead of using the generated texts as supervision for prompt tuning, a more explicit way is to directly use these texts as prompts or as a part of prompts (like concat[generated texts, learnable prompts]), I wonder if you have any experiments on this before finally choosing the supervision manner?

**Comment by EricTan7** [comment]
> > Thanks for your attention to our work. We plan to release our code within the forthcoming two weeks.
> 
> Thanks for your reply! After reading the paper, I got a few questions willing to have a discussion: -The prompt is tuned by the supervision from texts, while the texts are generated from MiniGPT, so is it reasonable to say that the prompt learning actually benefits from MiniGPT? -Instead of using the generated texts as supervision for prompt tuning, a more explicit way is to directly use these texts as prompts or as a part of prompts (like concat[generated texts, learnable prompts]), I wonder if you have any experiments on this before finally choosing the supervision manner?

1. MiniGPT-4 is introduced only during the training phase and does not cause information leakage in the test phase. Besides, the enhancement brought to visual tasks by general knowledge of large models is indeed highly interesting, which is something we aim to share with the community. We also hope this work can inspire more resource-efficient ways on this.
2. Actually we haven’t done such trials. It seems interesting to concat generated texts and prompts, but notice that the texts are not available during inference.

**Comment by xingbw** [comment]
Thanks! I think maybe I neglected the condition that miniGPT-4 is only used in training.
Looking forward to the code!
