### ISSUE TITLE
Lora_conv2d' object has no attribute 'weight‘

### ISSUE THREAD

**Issue by SNJ529** [EricTan7/TGP-T#3]
Hello, I encountered some issues while trying to replicate your experiment. When I switch the model to model_lora, the model fails to run properly and throws an error "AttributeError: 'Lora_conv2d' object has no attribute 'weight'". Could you please provide the correct way to switch models? I only changed the trainer's name part from TGPT to TGPT_lora in caltech101.yaml. I hope to receive your reply, thank you!

**Comment by EricTan7** [comment]
It seems the problem is on the loralib, as mentioned in [https://github.com/microsoft/LoRA/issues/134](url).
Try to switch to `loralib-0.1.1` to fix the problem.

**Comment by EricTan7** [comment]
It seems the problem is on the loralib, as mentioned in microsoft/LORA#134
Try to switch to `loralib-0.1.1` to fix the problem.
