### ISSUE TITLE
excellent work, did you evaluate the performance on base-to-novel generalization?

### ISSUE THREAD

**Issue by StellarOdys2ey** [EricTan7/TGP-T#5]
I found you have defined the subsample_classes function in datasates/basic.py，so have you conducted the same base-to-novel experiment as mentioned in other prompt-tuning methods through this function?

**Comment by EricTan7** [comment]
Hi, the proposed method excels primarily in enhancing few-shot classification tasks. We did not conduct experiments on base-to-novel setting.
